language: python
cache: pip
matrix:
  include:
    - python: 3.5
      env:
        - TOXENV=py35
        - CIBW_BUILD=cp35-*
    - python: 3.6
      env:
        - TOXENV=py36
        - CIBW_BUILD=cp36-*
    - python: 3.7
      env:
        - TOXENV=py37
        - CIBW_BUILD=cp37-*
    - python: 3.8
      env:
        - TOXENV=py38,doctest
        - CIBW_BUILD=cp38-*

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]]; then sudo apt-get install -y pandoc; fi
  - pip install tox coverage codecov cibuildwheel twine

script:
  - tox

after_success:
  - tox -e coverage
  - coverage report xml
  - codecov

before_deploy:
  - cibuildwheel --output-dir wheelhouse

deploy:
  - provider: script
    skip_cleanup: true
    script: env TWINE_USERNAME=__token__ TWINE_PASSWORD=$PYPI_PASSWORD twine upload --skip-existing wheelhouse/*.whl
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: env TWINE_USERNAME=__token__ TWINE_PASSWORD=$TESTPYPI_PASSWORD twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    on:
      tags: true
      all_branches: true