dist: xenial
language: python
cache: pip

python:
  - "2.7"
  - "3.5"
  - "3.7"
  #- "pypy3.5"  fails due to timing tests

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then sudo apt-get install -y pandoc; fi

install:
  - pip install codecov numpy pytest-cov pytest-timeout
  - pip install -e .

script:
  - pytest --cov="seqtools" --cov-config="setup.cfg" --cov-report=
  - coverage xml
  - codecov --file=coverage.xml
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install nose sphinx ipython ipykernel nbconvert nbsphinx Pillow scikit-learn scipy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then python -m sphinx -M doctest docs docs/_build; fi

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    branch: master
    python: "3.7"
